[model]
model_name = "Glow_TTS"
length_scale = 1.0
inference_noise_scale = 0.33  

[model.encoder]
num_chars = 47
out_channels = 80
hidden_channels = 256
hidden_channels_dp = 400
encoder_type = "rel_pos_transformer"
dropout_p_dp = 0.1
mean_only = true
use_prenet = true
c_in_channels = 0

[model.encoder.encoder_params]
kernel_size = 3
dropout_p = 0.1
num_layers = 12
num_heads = 8
hidden_channels_ffn = 1024


[model.decoder]
in_channels = 80
hidden_channels = 256
kernel_size = 5
dilation_rate = 1
num_flow_blocks = 16
num_coupling_layers = 6
dropout_p = 0.05
num_splits = 4
num_squeeze = 2
sigmoid_scale = false
c_in_channels = 0



[train]
data_dep_init_steps = 80
epochs= 150
print_step = 20
save_step = 5000
use_scheduler = false
grad_clip = 5.0
output_path = "Glow-TTS_output"
mandarin_file = "data/mandarin.csv"
cantonese_file = "data/cantonese.csv"
root_path = "data/AItts"
logs_step = 20
mandarin_num=49730
cantonese_num=18975
tensorboard_logs_dir =  "Glow-TTS_logs"
device = "cuda:1"

[dataloader]
batch_size = 40
shuffle = true


[optimizer]
type = "AdamW"
[optimizer.params]
lr=1e-5
betas=[0.9, 0.998]
weight_decay=5e-3

[scheduler]
type = "NoamLR"
[scheduler.params]
warmup_steps = 3000